#
# fabooh blink makefile
#

PROJECT ?= nokia5110_logo
LIBS ?=

include ../../../common_board.mk

ifneq ($(filter $(BOARD),msp430g2553in20 msp430g2452in20),)
include ../../../common.mk
else
include ../../../common_empty.mk
endif
