all:
	make -C sin_table all
	make -C cordic all
	make -C fixmath all

clean:
	make -C sin_table clean
	make -C cordic clean
	make -C fixmath clean

install: all
	make -C sin_table install
	make -C cordic install
	make -C fixmath install

