all:
	make -C armmath all
	make -C cordic all
	make -C fixmath all
	make -C sin_table all

clean:
	make -C armmath clean
	make -C cordic clean
	make -C fixmath clean
	make -C sin_table clean

install: all
	make -C armmath install
	make -C cordic install
	make -C fixmath install
	make -C sin_table install

