#
# fabooh blink makefile
#

PROJECT ?= ws2811_basic
LIBS ?=

include ../../../common_board.mk

ifeq ($(BOARD),msp430g2553in20)
 include ../../../common.mk
else
 include ../../../common_empty.mk
endif
