#
# fabooh blink makefile
#

TARGET   ?= avr910
LDLIBS   ?=
USEROBJS = 910.o

include ../../../common_board.mk

ifeq ($(BOARD),msp430g2553in20)
include ../../../common.mk
else
include ../../../common_empty.mk
endif

